#!/usr/bin/env python3
"""Inline the landing page's icons as SVG, from the subset font itself.

Why: the landing page is a static file served to cheap phones on slow networks.
An icon font can fail there — blocked request, stale immutable cache, a WebView
that mangles variable fonts — and every failure renders the icon's literal name
("keyboard_arrow_down") into the layout, shattering it. Inline SVG cannot fail:
no request, no cache, no font engine, and it prints.

The outlines come from public/fonts/material-symbols.woff2, so the glyphs are
the same ones the app shows — redrawn by nobody. Run it after adding an icon:

    python3 scripts/landing-icons.py

It writes the <symbol> block to stdout; paste it into index.html's hidden
sprite (or let it do that with --write).
"""
import sys
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen

NAMES = [
    'add_business', 'arrow_forward', 'balance', 'book', 'call', 'chat',
    'check', 'check_circle', 'close', 'content_cut', 'description',
    'directions_bike', 'download', 'edit_note', 'grass', 'groups', 'info',
    'keyboard_arrow_down', 'lock', 'login', 'menu', 'payments',
    'phone_android', 'print', 'science', 'sms', 'sync', 'verified_user',
    'visibility', 'vpn_key', 'wifi_off',
]


def ligature_glyph_ids(font):
    cmap = font.getBestCmap()
    lig_map = {}
    for lookup in font['GSUB'].table.LookupList.Lookup:
        for sub in lookup.SubTable:
            target = getattr(sub, 'ExtSubTable', sub)
            for first, ligs in getattr(target, 'ligatures', {}).items():
                for lig in ligs:
                    lig_map[tuple([first] + list(lig.Component))] = lig.LigGlyph
    return cmap, lig_map


def main():
    font = TTFont('public/fonts/material-symbols.woff2')
    upm = font['head'].unitsPerEm
    cmap, lig_map = ligature_glyph_ids(font)
    glyph_set = font.getGlyphSet()
    scale = 24 / upm

    out = [f'<!-- generated by scripts/landing-icons.py; do not hand-edit -->']
    missing = []
    for name in NAMES:
        seq = tuple(cmap[ord(c)] for c in name)
        gid = lig_map.get(seq)
        if gid is None:
            missing.append(name)
            continue
        pen = SVGPathPen(glyph_set)
        glyph_set[gid].draw(pen)
        d = pen.getCommands()
        out.append(
            f'<symbol id="i-{name}" viewBox="0 0 24 24">'
            f'<g transform="translate(0 24) scale({scale:.5f} {-scale:.5f})">'
            f'<path d="{d}" fill="currentColor"/></g></symbol>'
        )
    if missing:
        print('MISSING from subset font: ' + ' '.join(missing), file=sys.stderr)
        sys.exit(1)

    text = '<svg width="0" height="0" style="position:absolute" aria-hidden="true"><defs>\n' + '\n'.join(out) + '\n</defs></svg>'
    if '--write' in sys.argv:
        from pathlib import Path
        html = Path('index.html').read_text()
        start = html.find('<!--ICON-SPRITE-->')
        assert start > 0, 'index.html needs an <!--ICON-SPRITE--> marker'
        end = html.find('<!--/ICON-SPRITE-->')
        assert end > start
        html = html[:start] + '<!--ICON-SPRITE-->\n' + text + '\n<!--/ICON-SPRITE-->' + html[end + len('<!--/ICON-SPRITE-->'):]
        Path('index.html').write_text(html)
        print(f'sprite written: {len(out) - 1} symbols')
    else:
        print(text)


if __name__ == '__main__':
    main()
